#!/usr/bin/env python3
"""
register_universe.py — make "NSE All Equity" a selectable universe in the app.

    sudo -u breakout /opt/breakoutscanner/.venv/bin/python \
         /opt/breakoutscanner/register_universe.py --check
    sudo -u breakout /opt/breakoutscanner/.venv/bin/python \
         /opt/breakoutscanner/register_universe.py --apply

WHY THIS IS NEEDED
------------------
The Screener page queries the snapshot, so it already sees all 3,044 rows.
The main scan page does not: it calls universes.load_index_symbols(name), and
that function starts with

    if name not in INDEX_SLUGS:  ->  unavailable

so a universe that is not an NSE index literally cannot be chosen. This adds
one entry to INDEX_SLUGS and writes the constituent cache the loader reads,
which is DATA_DIR / f"{slug}_symbols.csv".

WHAT IT DOES NOT ASSUME
-----------------------
It reads an EXISTING cache file to copy the column layout instead of inventing
one. A CSV with the wrong header does not raise here — load_index_symbols
returns [] when "symbol" is missing from the columns, so the universe would
simply appear in the dropdown and scan nothing. That silent-empty outcome is
the failure mode this whole session has been about, so the script verifies by
calling load_index_symbols() and refuses to claim success on a short list.

ONE THING TO KNOW
-----------------
universes.refresh_all() iterates INDEX_REGISTRY and re-downloads each index
from NSE. There is no NSE archive URL for "every listed stock", so this entry
will report 0 there and log a failure. That is cosmetic — the cache file is
regenerated by build_nse_universe.py, not by NSE — but it will look alarming
in that one output, so it is worth knowing in advance rather than discovering.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

G, R, Y, C, B, X = ("\033[32m", "\033[31m", "\033[33m",
                    "\033[36m", "\033[1m", "\033[0m")

NAME = "NSE All Equity"
SLUG = "nse_all_equity"
SYMBOLS_FILE = "/opt/breakoutscanner/nse_all_equity.txt"
ANCHOR = "INDEX_SLUGS = {"


def hdr(s): print(f"\n{C}{'=' * 64}\n== {s}\n{'=' * 64}{X}")
def ok(s):  print(f"  {G}ok  {X} {s}")
def bad(s): print(f"  {R}FAIL{X} {s}")
def warn(s): print(f"  {Y}warn{X} {s}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_const", const="check", dest="mode")
    ap.add_argument("--apply", action="store_const", const="apply", dest="mode")
    ap.add_argument("--symbols", default=SYMBOLS_FILE)
    a = ap.parse_args()
    mode = a.mode or "check"

    hdr("1. the pieces this needs")
    try:
        import universes
    except Exception as e:
        bad(f"cannot import universes: {e}")
        return 2
    upath = os.path.abspath(universes.__file__)
    ok(f"universes.py {upath}")

    if not hasattr(universes, "INDEX_SLUGS"):
        bad("universes.INDEX_SLUGS not found")
        return 2
    ok(f"INDEX_SLUGS has {len(universes.INDEX_SLUGS)} entries: "
       f"{', '.join(list(universes.INDEX_SLUGS)[:6])}")

    data_dir = getattr(universes, "DATA_DIR", None)
    if data_dir is None or not os.path.isdir(str(data_dir)):
        bad(f"universes.DATA_DIR missing or not a directory: {data_dir!r}")
        return 2
    data_dir = str(data_dir)
    ok(f"DATA_DIR {data_dir}")

    if not os.path.isfile(a.symbols):
        bad(f"{a.symbols} not found — run build_nse_universe.py --apply first")
        return 2
    with open(a.symbols) as fh:
        syms = sorted({l.strip().upper() for l in fh
                       if l.strip() and not l.startswith("#")})
    ok(f"{len(syms):,} symbols in {a.symbols}")

    # ── copy an existing cache file's layout ───────────────────────────────
    hdr("2. the column layout of an existing cache")
    donor = None
    for n, slug in universes.INDEX_SLUGS.items():
        p = os.path.join(data_dir, f"{slug}_symbols.csv")
        if os.path.isfile(p):
            with open(p, newline="", errors="replace") as fh:
                rows = list(csv.reader(fh))
            if rows:
                donor = (n, p, rows[0])
                break
    if donor is None:
        bad("no existing *_symbols.csv to copy the layout from")
        return 3
    dname, dpath, header = donor
    ok(f"donor {dname}: {os.path.basename(dpath)}")
    print(f"       header: {header}")
    lower = [h.strip().lower() for h in header]
    if "symbol" not in lower:
        bad("donor has no 'symbol' column — layout unclear, refusing")
        return 3
    sym_col = lower.index("symbol")
    ok(f"'symbol' is column {sym_col} of {len(header)}")

    out_path = os.path.join(data_dir, f"{SLUG}_symbols.csv")
    print(f"\n  would write   {out_path}")
    print(f"  would add     INDEX_SLUGS[{NAME!r}] = {SLUG!r}")
    already = NAME in universes.INDEX_SLUGS
    if already:
        warn(f"{NAME!r} is already registered — will refresh the file only")

    if mode == "check":
        print(f"\n{Y}--check only. Nothing written.{X}")
        return 0

    # ── write the constituent cache ────────────────────────────────────────
    hdr("3. writing the constituent cache")
    try:
        with open(out_path, "w", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(header)
            for s in syms:
                row = [""] * len(header)
                row[sym_col] = s
                w.writerow(row)
    except OSError as e:
        bad(f"cannot write {out_path}: {e}")
        return 4
    ok(f"wrote {len(syms):,} rows to {out_path}")

    # ── register the name ──────────────────────────────────────────────────
    hdr("4. registering the name")
    if already:
        ok("already in INDEX_SLUGS — no source change needed")
    else:
        src = open(upath, errors="replace").read()
        if src.count(ANCHOR) != 1:
            bad(f"expected exactly one {ANCHOR!r}, found {src.count(ANCHOR)}")
            print("  Refusing to edit. Add this line yourself inside "
                  "INDEX_SLUGS:")
            print(f'      "{NAME}": "{SLUG}",')
            return 5
        backup = f"{upath}.backup-{datetime.now():%F-%H%M%S}"
        shutil.copy2(upath, backup)
        ok(f"backup {backup}")
        new = src.replace(
            ANCHOR,
            ANCHOR + f'\n    "{NAME}": "{SLUG}",'
                     f'  # every listed NSE equity; cache written by'
                     f' build_nse_universe.py, not downloaded from NSE',
            1)
        import py_compile
        import tempfile
        t = tempfile.NamedTemporaryFile("w", suffix=".py", delete=False)
        t.write(new)
        t.close()
        try:
            py_compile.compile(t.name, cfile=t.name + "c", doraise=True)
        except py_compile.PyCompileError as e:
            bad(f"patched universes.py does not compile: {e}")
            os.unlink(t.name)
            return 5
        finally:
            if os.path.exists(t.name + "c"):
                os.unlink(t.name + "c")
        st = os.stat(upath)
        shutil.copyfile(t.name, upath)
        os.chmod(upath, st.st_mode)
        os.unlink(t.name)
        ok("INDEX_SLUGS entry added")

    # ── the only check that matters ────────────────────────────────────────
    hdr("5. does the app load it?")
    # Re-import from disk: the module in memory predates the edit.
    import importlib
    importlib.reload(universes)
    got = []
    try:
        got = universes.load_index_symbols(NAME)
    except Exception as e:
        bad(f"load_index_symbols({NAME!r}) raised {type(e).__name__}: {e}")
        return 6
    if len(got) < len(syms) * 0.95:
        bad(f"loaded only {len(got):,} of {len(syms):,} — not trusting this")
        print("  A universe that loads short scans short, and reports nothing "
              "missing.")
        return 6
    ok(f"load_index_symbols({NAME!r}) -> {len(got):,} symbols")
    ok(f"registry is now: {', '.join(universes.INDEX_REGISTRY)}")

    hdr("done")
    print(f"""  Restart so the running app picks up the new registry:

      sudo systemctl restart breakoutscanner

  "{NAME}" will then appear in the universe picker alongside the
  index segments.

  {Y}Note: universes.refresh_all() will report this entry as FAILED,
  because there is no NSE archive URL for "every listed stock". The
  cache is regenerated by build_nse_universe.py instead. Cosmetic,
  but it will look like a broken index in that one output.{X}""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
